apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kc20mjk68-dotnet-basic
  janus-idp.io/tekton: kc20mjk68-dotnet-basic
  backstage.io/kubernetes-id: kc20mjk68-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kc20mjk68-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
