apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kc20mjk68-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kc20mjk68-dotnet-basic-gitops